import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from './../(components)/header/header';
import Footer from './../(components)/footer/footer';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faLocationDot, faShareNodes } from '@fortawesome/free-solid-svg-icons';
import { faPhone } from '@fortawesome/free-solid-svg-icons';
import { faEnvelope } from '@fortawesome/free-solid-svg-icons';
import { faTwitter, faFacebook, faInstagram } from '@fortawesome/free-brands-svg-icons';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Naadamfest',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <>   
   <Header />
            <main className={inter.className}>{children}
              <div id="fixed-social">
                <div>
                  <a href="#" className="fixed-facebook" target="_blank"> <FontAwesomeIcon icon={faFacebook} className='socialicon' /> <span>Facebook</span></a>
                </div>
                <div>
                  <a href="#" className="fixed-twitter" target="_blank"> <FontAwesomeIcon icon={faTwitter} className='socialicon' /><span>Twitter</span></a>
                </div>
                <div>
                  <a href="#" className="fixed-instagrem" target="_blank"><FontAwesomeIcon icon={faInstagram} className='socialicon' /><span>Instagram</span></a>
                </div>
                <div>
                  <a href="#" className="fixed-tumblr" target="_blank"><FontAwesomeIcon icon={faShareNodes} className='socialicon' /> <span>Share</span></a>
                </div>
              </div>
            </main>
        <Footer />
        </>
     
  )
}
